/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ConnectionResponse;
import org.openapitools.client.model.ConnectionStatusRequest;
import org.openapitools.client.model.ConnectionStatusResponse;
import org.openapitools.client.model.CreateOrganizationConnectionRequest;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetAllOrganizationConnections200Response;
import org.openapitools.client.model.OrganizationConnectionRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationConnectionsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationConnectionsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationConnectionsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createOrganizationConnection
     * @param orgId Organization ID (required)
     * @param createOrganizationConnectionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createOrganizationConnectionCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateOrganizationConnectionRequest createOrganizationConnectionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createOrganizationConnectionRequest;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createOrganizationConnectionValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateOrganizationConnectionRequest createOrganizationConnectionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling createOrganizationConnection(Async)");
        }

        // verify the required parameter 'createOrganizationConnectionRequest' is set
        if (createOrganizationConnectionRequest == null) {
            throw new ApiException("Missing the required parameter 'createOrganizationConnectionRequest' when calling createOrganizationConnection(Async)");
        }

        return createOrganizationConnectionCall(orgId, createOrganizationConnectionRequest, _callback);

    }

    /**
     * Create Organization Connection
     * Create a new identity provider connection for an organization
     * @param orgId Organization ID (required)
     * @param createOrganizationConnectionRequest  (required)
     * @return ConnectionResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionResponse createOrganizationConnection(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateOrganizationConnectionRequest createOrganizationConnectionRequest) throws ApiException {
        ApiResponse<ConnectionResponse> localVarResp = createOrganizationConnectionWithHttpInfo(orgId, createOrganizationConnectionRequest);
        return localVarResp.getData();
    }

    /**
     * Create Organization Connection
     * Create a new identity provider connection for an organization
     * @param orgId Organization ID (required)
     * @param createOrganizationConnectionRequest  (required)
     * @return ApiResponse&lt;ConnectionResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionResponse> createOrganizationConnectionWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateOrganizationConnectionRequest createOrganizationConnectionRequest) throws ApiException {
        okhttp3.Call localVarCall = createOrganizationConnectionValidateBeforeCall(orgId, createOrganizationConnectionRequest, null);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Organization Connection (asynchronously)
     * Create a new identity provider connection for an organization
     * @param orgId Organization ID (required)
     * @param createOrganizationConnectionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createOrganizationConnectionAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateOrganizationConnectionRequest createOrganizationConnectionRequest, final ApiCallback<ConnectionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createOrganizationConnectionValidateBeforeCall(orgId, createOrganizationConnectionRequest, _callback);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteOrganizationConnection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationConnectionCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteOrganizationConnectionValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling deleteOrganizationConnection(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling deleteOrganizationConnection(Async)");
        }

        return deleteOrganizationConnectionCall(orgId, connId, _callback);

    }

    /**
     * Delete Organization Connection
     * Delete an identity provider connection from an organization
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return DeleteResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public DeleteResponse deleteOrganizationConnection(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        ApiResponse<DeleteResponse> localVarResp = deleteOrganizationConnectionWithHttpInfo(orgId, connId);
        return localVarResp.getData();
    }

    /**
     * Delete Organization Connection
     * Delete an identity provider connection from an organization
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return ApiResponse&lt;DeleteResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteResponse> deleteOrganizationConnectionWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        okhttp3.Call localVarCall = deleteOrganizationConnectionValidateBeforeCall(orgId, connId, null);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Organization Connection (asynchronously)
     * Delete an identity provider connection from an organization
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteOrganizationConnectionAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback<DeleteResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteOrganizationConnectionValidateBeforeCall(orgId, connId, _callback);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllOrganizationConnections
     * @param orgId Organization ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllOrganizationConnectionsCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllOrganizationConnectionsValidateBeforeCall(@javax.annotation.Nonnull String orgId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling getAllOrganizationConnections(Async)");
        }

        return getAllOrganizationConnectionsCall(orgId, _callback);

    }

    /**
     * Get All Organization Connections
     * Get all identity provider connections for an organization
     * @param orgId Organization ID (required)
     * @return GetAllOrganizationConnections200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public GetAllOrganizationConnections200Response getAllOrganizationConnections(@javax.annotation.Nonnull String orgId) throws ApiException {
        ApiResponse<GetAllOrganizationConnections200Response> localVarResp = getAllOrganizationConnectionsWithHttpInfo(orgId);
        return localVarResp.getData();
    }

    /**
     * Get All Organization Connections
     * Get all identity provider connections for an organization
     * @param orgId Organization ID (required)
     * @return ApiResponse&lt;GetAllOrganizationConnections200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetAllOrganizationConnections200Response> getAllOrganizationConnectionsWithHttpInfo(@javax.annotation.Nonnull String orgId) throws ApiException {
        okhttp3.Call localVarCall = getAllOrganizationConnectionsValidateBeforeCall(orgId, null);
        Type localVarReturnType = new TypeToken<GetAllOrganizationConnections200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Organization Connections (asynchronously)
     * Get all identity provider connections for an organization
     * @param orgId Organization ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllOrganizationConnectionsAsync(@javax.annotation.Nonnull String orgId, final ApiCallback<GetAllOrganizationConnections200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllOrganizationConnectionsValidateBeforeCall(orgId, _callback);
        Type localVarReturnType = new TypeToken<GetAllOrganizationConnections200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getOrganizationConnection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationConnectionCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getOrganizationConnectionValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling getOrganizationConnection(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling getOrganizationConnection(Async)");
        }

        return getOrganizationConnectionCall(orgId, connId, _callback);

    }

    /**
     * Get Organization Connection
     * Get details of a specific identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return ConnectionResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionResponse getOrganizationConnection(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        ApiResponse<ConnectionResponse> localVarResp = getOrganizationConnectionWithHttpInfo(orgId, connId);
        return localVarResp.getData();
    }

    /**
     * Get Organization Connection
     * Get details of a specific identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return ApiResponse&lt;ConnectionResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionResponse> getOrganizationConnectionWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        okhttp3.Call localVarCall = getOrganizationConnectionValidateBeforeCall(orgId, connId, null);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Organization Connection (asynchronously)
     * Get details of a specific identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getOrganizationConnectionAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback<ConnectionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getOrganizationConnectionValidateBeforeCall(orgId, connId, _callback);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateConnectionStatus
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param connectionStatusRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateConnectionStatusCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull ConnectionStatusRequest connectionStatusRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = connectionStatusRequest;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}/status"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateConnectionStatusValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull ConnectionStatusRequest connectionStatusRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling updateConnectionStatus(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling updateConnectionStatus(Async)");
        }

        // verify the required parameter 'connectionStatusRequest' is set
        if (connectionStatusRequest == null) {
            throw new ApiException("Missing the required parameter 'connectionStatusRequest' when calling updateConnectionStatus(Async)");
        }

        return updateConnectionStatusCall(orgId, connId, connectionStatusRequest, _callback);

    }

    /**
     * Update Organization Connection Status
     * Update the active status of an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param connectionStatusRequest  (required)
     * @return ConnectionStatusResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionStatusResponse updateConnectionStatus(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull ConnectionStatusRequest connectionStatusRequest) throws ApiException {
        ApiResponse<ConnectionStatusResponse> localVarResp = updateConnectionStatusWithHttpInfo(orgId, connId, connectionStatusRequest);
        return localVarResp.getData();
    }

    /**
     * Update Organization Connection Status
     * Update the active status of an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param connectionStatusRequest  (required)
     * @return ApiResponse&lt;ConnectionStatusResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionStatusResponse> updateConnectionStatusWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull ConnectionStatusRequest connectionStatusRequest) throws ApiException {
        okhttp3.Call localVarCall = updateConnectionStatusValidateBeforeCall(orgId, connId, connectionStatusRequest, null);
        Type localVarReturnType = new TypeToken<ConnectionStatusResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Organization Connection Status (asynchronously)
     * Update the active status of an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param connectionStatusRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateConnectionStatusAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull ConnectionStatusRequest connectionStatusRequest, final ApiCallback<ConnectionStatusResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateConnectionStatusValidateBeforeCall(orgId, connId, connectionStatusRequest, _callback);
        Type localVarReturnType = new TypeToken<ConnectionStatusResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateOrganizationConnection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param organizationConnectionRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOrganizationConnectionCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull OrganizationConnectionRequest organizationConnectionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = organizationConnectionRequest;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateOrganizationConnectionValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull OrganizationConnectionRequest organizationConnectionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling updateOrganizationConnection(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling updateOrganizationConnection(Async)");
        }

        // verify the required parameter 'organizationConnectionRequest' is set
        if (organizationConnectionRequest == null) {
            throw new ApiException("Missing the required parameter 'organizationConnectionRequest' when calling updateOrganizationConnection(Async)");
        }

        return updateOrganizationConnectionCall(orgId, connId, organizationConnectionRequest, _callback);

    }

    /**
     * Update Organization Connection
     * Update an identity provider connection&#39;s configuration
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param organizationConnectionRequest  (required)
     * @return ConnectionResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionResponse updateOrganizationConnection(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull OrganizationConnectionRequest organizationConnectionRequest) throws ApiException {
        ApiResponse<ConnectionResponse> localVarResp = updateOrganizationConnectionWithHttpInfo(orgId, connId, organizationConnectionRequest);
        return localVarResp.getData();
    }

    /**
     * Update Organization Connection
     * Update an identity provider connection&#39;s configuration
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param organizationConnectionRequest  (required)
     * @return ApiResponse&lt;ConnectionResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionResponse> updateOrganizationConnectionWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull OrganizationConnectionRequest organizationConnectionRequest) throws ApiException {
        okhttp3.Call localVarCall = updateOrganizationConnectionValidateBeforeCall(orgId, connId, organizationConnectionRequest, null);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Organization Connection (asynchronously)
     * Update an identity provider connection&#39;s configuration
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param organizationConnectionRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateOrganizationConnectionAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull OrganizationConnectionRequest organizationConnectionRequest, final ApiCallback<ConnectionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateOrganizationConnectionValidateBeforeCall(orgId, connId, organizationConnectionRequest, _callback);
        Type localVarReturnType = new TypeToken<ConnectionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
