/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ConnectionGroupRoleRequest;
import org.openapitools.client.model.ConnectionGroupRoleResponse;
import org.openapitools.client.model.CreateConnectionGroupRoleRequest;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetAllConnectionGroupRoles200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationConnectionGroupRolesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationConnectionGroupRolesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationConnectionGroupRolesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createConnectionGroupRole
     * @param connId Organization Connection ID (required)
     * @param orgId Organization ID (required)
     * @param createConnectionGroupRoleRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createConnectionGroupRoleCall(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createConnectionGroupRoleRequest;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}/grouproles"
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()))
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createConnectionGroupRoleValidateBeforeCall(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling createConnectionGroupRole(Async)");
        }

        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling createConnectionGroupRole(Async)");
        }

        // verify the required parameter 'createConnectionGroupRoleRequest' is set
        if (createConnectionGroupRoleRequest == null) {
            throw new ApiException("Missing the required parameter 'createConnectionGroupRoleRequest' when calling createConnectionGroupRole(Async)");
        }

        return createConnectionGroupRoleCall(connId, orgId, createConnectionGroupRoleRequest, _callback);

    }

    /**
     * Create Organization Connection Group Roles
     * Create a new group-to-role mapping for an identity provider connection
     * @param connId Organization Connection ID (required)
     * @param orgId Organization ID (required)
     * @param createConnectionGroupRoleRequest  (required)
     * @return ConnectionGroupRoleResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionGroupRoleResponse createConnectionGroupRole(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest) throws ApiException {
        ApiResponse<ConnectionGroupRoleResponse> localVarResp = createConnectionGroupRoleWithHttpInfo(connId, orgId, createConnectionGroupRoleRequest);
        return localVarResp.getData();
    }

    /**
     * Create Organization Connection Group Roles
     * Create a new group-to-role mapping for an identity provider connection
     * @param connId Organization Connection ID (required)
     * @param orgId Organization ID (required)
     * @param createConnectionGroupRoleRequest  (required)
     * @return ApiResponse&lt;ConnectionGroupRoleResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionGroupRoleResponse> createConnectionGroupRoleWithHttpInfo(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest) throws ApiException {
        okhttp3.Call localVarCall = createConnectionGroupRoleValidateBeforeCall(connId, orgId, createConnectionGroupRoleRequest, null);
        Type localVarReturnType = new TypeToken<ConnectionGroupRoleResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Organization Connection Group Roles (asynchronously)
     * Create a new group-to-role mapping for an identity provider connection
     * @param connId Organization Connection ID (required)
     * @param orgId Organization ID (required)
     * @param createConnectionGroupRoleRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createConnectionGroupRoleAsync(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest, final ApiCallback<ConnectionGroupRoleResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createConnectionGroupRoleValidateBeforeCall(connId, orgId, createConnectionGroupRoleRequest, _callback);
        Type localVarReturnType = new TypeToken<ConnectionGroupRoleResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteConnectionGroupRole
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteConnectionGroupRoleCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}/grouproles/{groupRoleId}"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()))
            .replace("{" + "groupRoleId" + "}", localVarApiClient.escapeString(groupRoleId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteConnectionGroupRoleValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling deleteConnectionGroupRole(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling deleteConnectionGroupRole(Async)");
        }

        // verify the required parameter 'groupRoleId' is set
        if (groupRoleId == null) {
            throw new ApiException("Missing the required parameter 'groupRoleId' when calling deleteConnectionGroupRole(Async)");
        }

        return deleteConnectionGroupRoleCall(orgId, connId, groupRoleId, _callback);

    }

    /**
     * Delete Organization Connection Group Roles
     * Delete a specific group-to-role mapping
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @return DeleteResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public DeleteResponse deleteConnectionGroupRole(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId) throws ApiException {
        ApiResponse<DeleteResponse> localVarResp = deleteConnectionGroupRoleWithHttpInfo(orgId, connId, groupRoleId);
        return localVarResp.getData();
    }

    /**
     * Delete Organization Connection Group Roles
     * Delete a specific group-to-role mapping
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @return ApiResponse&lt;DeleteResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteResponse> deleteConnectionGroupRoleWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId) throws ApiException {
        okhttp3.Call localVarCall = deleteConnectionGroupRoleValidateBeforeCall(orgId, connId, groupRoleId, null);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete Organization Connection Group Roles (asynchronously)
     * Delete a specific group-to-role mapping
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteConnectionGroupRoleAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, final ApiCallback<DeleteResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteConnectionGroupRoleValidateBeforeCall(orgId, connId, groupRoleId, _callback);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllConnectionGroupRoles
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllConnectionGroupRolesCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}/grouproles"
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()))
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllConnectionGroupRolesValidateBeforeCall(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling getAllConnectionGroupRoles(Async)");
        }

        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling getAllConnectionGroupRoles(Async)");
        }

        return getAllConnectionGroupRolesCall(orgId, connId, _callback);

    }

    /**
     * Get All Organization Connection Group Roles
     * Get all group-to-role mappings for an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return GetAllConnectionGroupRoles200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public GetAllConnectionGroupRoles200Response getAllConnectionGroupRoles(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        ApiResponse<GetAllConnectionGroupRoles200Response> localVarResp = getAllConnectionGroupRolesWithHttpInfo(orgId, connId);
        return localVarResp.getData();
    }

    /**
     * Get All Organization Connection Group Roles
     * Get all group-to-role mappings for an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @return ApiResponse&lt;GetAllConnectionGroupRoles200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetAllConnectionGroupRoles200Response> getAllConnectionGroupRolesWithHttpInfo(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId) throws ApiException {
        okhttp3.Call localVarCall = getAllConnectionGroupRolesValidateBeforeCall(orgId, connId, null);
        Type localVarReturnType = new TypeToken<GetAllConnectionGroupRoles200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Organization Connection Group Roles (asynchronously)
     * Get all group-to-role mappings for an identity provider connection
     * @param orgId Organization ID (required)
     * @param connId Organization Connection ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllConnectionGroupRolesAsync(@javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull String connId, final ApiCallback<GetAllConnectionGroupRoles200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllConnectionGroupRolesValidateBeforeCall(orgId, connId, _callback);
        Type localVarReturnType = new TypeToken<GetAllConnectionGroupRoles200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateConnectionGroupRole
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param orgId Organization ID (required)
     * @param connectionGroupRoleRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateConnectionGroupRoleCall(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull ConnectionGroupRoleRequest connectionGroupRoleRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = connectionGroupRoleRequest;

        // create path and map variables
        String localVarPath = "/organizations/{orgId}/connections/{connId}/grouproles/{groupRoleId}"
            .replace("{" + "connId" + "}", localVarApiClient.escapeString(connId.toString()))
            .replace("{" + "groupRoleId" + "}", localVarApiClient.escapeString(groupRoleId.toString()))
            .replace("{" + "orgId" + "}", localVarApiClient.escapeString(orgId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateConnectionGroupRoleValidateBeforeCall(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull ConnectionGroupRoleRequest connectionGroupRoleRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'connId' is set
        if (connId == null) {
            throw new ApiException("Missing the required parameter 'connId' when calling updateConnectionGroupRole(Async)");
        }

        // verify the required parameter 'groupRoleId' is set
        if (groupRoleId == null) {
            throw new ApiException("Missing the required parameter 'groupRoleId' when calling updateConnectionGroupRole(Async)");
        }

        // verify the required parameter 'orgId' is set
        if (orgId == null) {
            throw new ApiException("Missing the required parameter 'orgId' when calling updateConnectionGroupRole(Async)");
        }

        // verify the required parameter 'connectionGroupRoleRequest' is set
        if (connectionGroupRoleRequest == null) {
            throw new ApiException("Missing the required parameter 'connectionGroupRoleRequest' when calling updateConnectionGroupRole(Async)");
        }

        return updateConnectionGroupRoleCall(connId, groupRoleId, orgId, connectionGroupRoleRequest, _callback);

    }

    /**
     * Update Organization Connection Group Roles
     * Update a specific group-to-role mapping
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param orgId Organization ID (required)
     * @param connectionGroupRoleRequest  (required)
     * @return ConnectionGroupRoleResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ConnectionGroupRoleResponse updateConnectionGroupRole(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull ConnectionGroupRoleRequest connectionGroupRoleRequest) throws ApiException {
        ApiResponse<ConnectionGroupRoleResponse> localVarResp = updateConnectionGroupRoleWithHttpInfo(connId, groupRoleId, orgId, connectionGroupRoleRequest);
        return localVarResp.getData();
    }

    /**
     * Update Organization Connection Group Roles
     * Update a specific group-to-role mapping
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param orgId Organization ID (required)
     * @param connectionGroupRoleRequest  (required)
     * @return ApiResponse&lt;ConnectionGroupRoleResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConnectionGroupRoleResponse> updateConnectionGroupRoleWithHttpInfo(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull ConnectionGroupRoleRequest connectionGroupRoleRequest) throws ApiException {
        okhttp3.Call localVarCall = updateConnectionGroupRoleValidateBeforeCall(connId, groupRoleId, orgId, connectionGroupRoleRequest, null);
        Type localVarReturnType = new TypeToken<ConnectionGroupRoleResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Organization Connection Group Roles (asynchronously)
     * Update a specific group-to-role mapping
     * @param connId Organization Connection ID (required)
     * @param groupRoleId Organization Connection Group Role ID (required)
     * @param orgId Organization ID (required)
     * @param connectionGroupRoleRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Status Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Status Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Status Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateConnectionGroupRoleAsync(@javax.annotation.Nonnull String connId, @javax.annotation.Nonnull String groupRoleId, @javax.annotation.Nonnull String orgId, @javax.annotation.Nonnull ConnectionGroupRoleRequest connectionGroupRoleRequest, final ApiCallback<ConnectionGroupRoleResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateConnectionGroupRoleValidateBeforeCall(connId, groupRoleId, orgId, connectionGroupRoleRequest, _callback);
        Type localVarReturnType = new TypeToken<ConnectionGroupRoleResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
