/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DefaultResponse;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetAllRoles200Response;
import org.openapitools.client.model.Role;
import org.openapitools.client.model.RoleByName200Response;
import org.openapitools.client.model.RolePostRequest;
import org.openapitools.client.model.RolesPutRequest;
import org.openapitools.client.model.TenantRole;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RolesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RolesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RolesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createRole
     * @param rolePostRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRoleCall(@javax.annotation.Nonnull RolePostRequest rolePostRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = rolePostRequest;

        // create path and map variables
        String localVarPath = "/roles";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRoleValidateBeforeCall(@javax.annotation.Nonnull RolePostRequest rolePostRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'rolePostRequest' is set
        if (rolePostRequest == null) {
            throw new ApiException("Missing the required parameter 'rolePostRequest' when calling createRole(Async)");
        }

        return createRoleCall(rolePostRequest, _callback);

    }

    /**
     * 
     * Create a new role in the tenant
     * @param rolePostRequest  (required)
     * @return TenantRole
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public TenantRole createRole(@javax.annotation.Nonnull RolePostRequest rolePostRequest) throws ApiException {
        ApiResponse<TenantRole> localVarResp = createRoleWithHttpInfo(rolePostRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Create a new role in the tenant
     * @param rolePostRequest  (required)
     * @return ApiResponse&lt;TenantRole&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TenantRole> createRoleWithHttpInfo(@javax.annotation.Nonnull RolePostRequest rolePostRequest) throws ApiException {
        okhttp3.Call localVarCall = createRoleValidateBeforeCall(rolePostRequest, null);
        Type localVarReturnType = new TypeToken<TenantRole>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Create a new role in the tenant
     * @param rolePostRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRoleAsync(@javax.annotation.Nonnull RolePostRequest rolePostRequest, final ApiCallback<TenantRole> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRoleValidateBeforeCall(rolePostRequest, _callback);
        Type localVarReturnType = new TypeToken<TenantRole>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteRole
     * @param id Role ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRoleCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/roles/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteRoleValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteRole(Async)");
        }

        return deleteRoleCall(id, _callback);

    }

    /**
     * 
     * Delete Role
     * @param id Role ID (required)
     * @return DeleteResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public DeleteResponse deleteRole(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<DeleteResponse> localVarResp = deleteRoleWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 
     * Delete Role
     * @param id Role ID (required)
     * @return ApiResponse&lt;DeleteResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteResponse> deleteRoleWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = deleteRoleValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Delete Role
     * @param id Role ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteRoleAsync(@javax.annotation.Nonnull String id, final ApiCallback<DeleteResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteRoleValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<DeleteResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllRoles
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllRolesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/roles";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllRolesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getAllRolesCall(_callback);

    }

    /**
     * 
     * Get all roles in the tenant
     * @return GetAllRoles200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public GetAllRoles200Response getAllRoles() throws ApiException {
        ApiResponse<GetAllRoles200Response> localVarResp = getAllRolesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * 
     * Get all roles in the tenant
     * @return ApiResponse&lt;GetAllRoles200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetAllRoles200Response> getAllRolesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getAllRolesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetAllRoles200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Get all roles in the tenant
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllRolesAsync(final ApiCallback<GetAllRoles200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllRolesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetAllRoles200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRoleById
     * @param id Role ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRoleByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/roles/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRoleByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getRoleById(Async)");
        }

        return getRoleByIdCall(id, _callback);

    }

    /**
     * 
     * Get details of a specific role by its ID
     * @param id Role ID (required)
     * @return Role
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public Role getRoleById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Role> localVarResp = getRoleByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 
     * Get details of a specific role by its ID
     * @param id Role ID (required)
     * @return ApiResponse&lt;Role&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Role> getRoleByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getRoleByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Role>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Get details of a specific role by its ID
     * @param id Role ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRoleByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<Role> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRoleByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Role>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for roleByName
     * @param name Role Name (required)
     * @param orgid Organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call roleByNameCall(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String orgid, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/roles/{name}/name"
            .replace("{" + "name" + "}", localVarApiClient.escapeString(name.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (orgid != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("orgid", orgid));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call roleByNameValidateBeforeCall(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String orgid, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling roleByName(Async)");
        }

        return roleByNameCall(name, orgid, _callback);

    }

    /**
     * Get Role by Name
     * This API is used to get the role by the role name.
     * @param name Role Name (required)
     * @param orgid Organization ID (optional)
     * @return RoleByName200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public RoleByName200Response roleByName(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String orgid) throws ApiException {
        ApiResponse<RoleByName200Response> localVarResp = roleByNameWithHttpInfo(name, orgid);
        return localVarResp.getData();
    }

    /**
     * Get Role by Name
     * This API is used to get the role by the role name.
     * @param name Role Name (required)
     * @param orgid Organization ID (optional)
     * @return ApiResponse&lt;RoleByName200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RoleByName200Response> roleByNameWithHttpInfo(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String orgid) throws ApiException {
        okhttp3.Call localVarCall = roleByNameValidateBeforeCall(name, orgid, null);
        Type localVarReturnType = new TypeToken<RoleByName200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Role by Name (asynchronously)
     * This API is used to get the role by the role name.
     * @param name Role Name (required)
     * @param orgid Organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call roleByNameAsync(@javax.annotation.Nonnull String name, @javax.annotation.Nullable String orgid, final ApiCallback<RoleByName200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = roleByNameValidateBeforeCall(name, orgid, _callback);
        Type localVarReturnType = new TypeToken<RoleByName200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for setDefaultRole
     * @param id Role ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setDefaultRoleCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/roles/{id}/default"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call setDefaultRoleValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling setDefaultRole(Async)");
        }

        return setDefaultRoleCall(id, _callback);

    }

    /**
     * 
     * Set Default Role
     * @param id Role ID (required)
     * @return DefaultResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public DefaultResponse setDefaultRole(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<DefaultResponse> localVarResp = setDefaultRoleWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 
     * Set Default Role
     * @param id Role ID (required)
     * @return ApiResponse&lt;DefaultResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DefaultResponse> setDefaultRoleWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = setDefaultRoleValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<DefaultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Set Default Role
     * @param id Role ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call setDefaultRoleAsync(@javax.annotation.Nonnull String id, final ApiCallback<DefaultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = setDefaultRoleValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<DefaultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRole
     * @param id Role ID (required)
     * @param rolesPutRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRoleCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RolesPutRequest rolesPutRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = rolesPutRequest;

        // create path and map variables
        String localVarPath = "/roles/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ClientIdAuth", "ClientSecretAuth", "M2MBearerAuth", "ApiKeyAuth", "ApiSecretAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRoleValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RolesPutRequest rolesPutRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateRole(Async)");
        }

        // verify the required parameter 'rolesPutRequest' is set
        if (rolesPutRequest == null) {
            throw new ApiException("Missing the required parameter 'rolesPutRequest' when calling updateRole(Async)");
        }

        return updateRoleCall(id, rolesPutRequest, _callback);

    }

    /**
     * 
     * Update a role&#39;s details by its ID
     * @param id Role ID (required)
     * @param rolesPutRequest  (required)
     * @return Role
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public Role updateRole(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RolesPutRequest rolesPutRequest) throws ApiException {
        ApiResponse<Role> localVarResp = updateRoleWithHttpInfo(id, rolesPutRequest);
        return localVarResp.getData();
    }

    /**
     * 
     * Update a role&#39;s details by its ID
     * @param id Role ID (required)
     * @param rolesPutRequest  (required)
     * @return ApiResponse&lt;Role&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Role> updateRoleWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RolesPutRequest rolesPutRequest) throws ApiException {
        okhttp3.Call localVarCall = updateRoleValidateBeforeCall(id, rolesPutRequest, null);
        Type localVarReturnType = new TypeToken<Role>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Update a role&#39;s details by its ID
     * @param id Role ID (required)
     * @param rolesPutRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK: The request was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request: The request could not be understood by the server due to malformed syntax. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden: The client does not have permission to access the resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found: The requested resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict: The request could not be completed due to a conflict with the current state of the resource. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error: The server encountered an unexpected error. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRoleAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull RolesPutRequest rolesPutRequest, final ApiCallback<Role> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRoleValidateBeforeCall(id, rolesPutRequest, _callback);
        Type localVarReturnType = new TypeToken<Role>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
