/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Invitation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetInvitationsByOrgId200Response
 */
public class GetInvitationsByOrgId200ResponseTest {
    private final GetInvitationsByOrgId200Response model = new GetInvitationsByOrgId200Response();

    /**
     * Model tests for GetInvitationsByOrgId200Response
     */
    @Test
    public void testGetInvitationsByOrgId200Response() {
        // TODO: test GetInvitationsByOrgId200Response
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

}
