/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OidcConnectionResponse
 */
public class OidcConnectionResponseTest {
    private final OidcConnectionResponse model = new OidcConnectionResponse();

    /**
     * Model tests for OidcConnectionResponse
     */
    @Test
    public void testOidcConnectionResponse() {
        // TODO: test OidcConnectionResponse
    }

    /**
     * Test the property 'authorizationUrl'
     */
    @Test
    public void authorizationUrlTest() {
        // TODO: test authorizationUrl
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'scopes'
     */
    @Test
    public void scopesTest() {
        // TODO: test scopes
    }

    /**
     * Test the property 'tokenAuthMethod'
     */
    @Test
    public void tokenAuthMethodTest() {
        // TODO: test tokenAuthMethod
    }

    /**
     * Test the property 'tokenUrl'
     */
    @Test
    public void tokenUrlTest() {
        // TODO: test tokenUrl
    }

    /**
     * Test the property 'userInfoUrl'
     */
    @Test
    public void userInfoUrlTest() {
        // TODO: test userInfoUrl
    }

    /**
     * Test the property 'connectionType'
     */
    @Test
    public void connectionTypeTest() {
        // TODO: test connectionType
    }

    /**
     * Test the property 'redirectURI'
     */
    @Test
    public void redirectURITest() {
        // TODO: test redirectURI
    }

}
