/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OrganizationsConnectionBaseAttributes;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationConnectionRequest
 */
public class OrganizationConnectionRequestTest {
    private final OrganizationConnectionRequest model = new OrganizationConnectionRequest();

    /**
     * Model tests for OrganizationConnectionRequest
     */
    @Test
    public void testOrganizationConnectionRequest() {
        // TODO: test OrganizationConnectionRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'connectionType'
     */
    @Test
    public void connectionTypeTest() {
        // TODO: test connectionType
    }

    /**
     * Test the property 'idPEntityId'
     */
    @Test
    public void idPEntityIdTest() {
        // TODO: test idPEntityId
    }

    /**
     * Test the property 'idPMetadataUrl'
     */
    @Test
    public void idPMetadataUrlTest() {
        // TODO: test idPMetadataUrl
    }

    /**
     * Test the property 'isIDPInitiated'
     */
    @Test
    public void isIDPInitiatedTest() {
        // TODO: test isIDPInitiated
    }

    /**
     * Test the property 'idPCertificate'
     */
    @Test
    public void idPCertificateTest() {
        // TODO: test idPCertificate
    }

    /**
     * Test the property 'authorizationUrl'
     */
    @Test
    public void authorizationUrlTest() {
        // TODO: test authorizationUrl
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'scopes'
     */
    @Test
    public void scopesTest() {
        // TODO: test scopes
    }

    /**
     * Test the property 'tokenAuthMethod'
     */
    @Test
    public void tokenAuthMethodTest() {
        // TODO: test tokenAuthMethod
    }

    /**
     * Test the property 'tokenUrl'
     */
    @Test
    public void tokenUrlTest() {
        // TODO: test tokenUrl
    }

    /**
     * Test the property 'userInfoUrl'
     */
    @Test
    public void userInfoUrlTest() {
        // TODO: test userInfoUrl
    }

}
