/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationsStatusResponse
 */
public class OrganizationsStatusResponseTest {
    private final OrganizationsStatusResponse model = new OrganizationsStatusResponse();

    /**
     * Model tests for OrganizationsStatusResponse
     */
    @Test
    public void testOrganizationsStatusResponse() {
        // TODO: test OrganizationsStatusResponse
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

}
