/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationsPolicyBaseMemberPolicy
 */
public class OrganizationsPolicyBaseMemberPolicyTest {
    private final OrganizationsPolicyBaseMemberPolicy model = new OrganizationsPolicyBaseMemberPolicy();

    /**
     * Model tests for OrganizationsPolicyBaseMemberPolicy
     */
    @Test
    public void testOrganizationsPolicyBaseMemberPolicy() {
        // TODO: test OrganizationsPolicyBaseMemberPolicy
    }

    /**
     * Test the property 'defaultMemberRole'
     */
    @Test
    public void defaultMemberRoleTest() {
        // TODO: test defaultMemberRole
    }

}
