/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateInvitationByInvitationIdRequest
 */
public class UpdateInvitationByInvitationIdRequestTest {
    private final UpdateInvitationByInvitationIdRequest model = new UpdateInvitationByInvitationIdRequest();

    /**
     * Model tests for UpdateInvitationByInvitationIdRequest
     */
    @Test
    public void testUpdateInvitationByInvitationIdRequest() {
        // TODO: test UpdateInvitationByInvitationIdRequest
    }

    /**
     * Test the property 'roleIds'
     */
    @Test
    public void roleIdsTest() {
        // TODO: test roleIds
    }

    /**
     * Test the property 'resendEmail'
     */
    @Test
    public void resendEmailTest() {
        // TODO: test resendEmail
    }

}
