/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OidcConnectionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-02T09:39:07.890516193Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class OidcConnectionResponse {
  public static final String SERIALIZED_NAME_AUTHORIZATION_URL = "AuthorizationUrl";
  @SerializedName(SERIALIZED_NAME_AUTHORIZATION_URL)
  @javax.annotation.Nullable
  private String authorizationUrl;

  public static final String SERIALIZED_NAME_CLIENT_ID = "ClientId";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nullable
  private String clientId;

  public static final String SERIALIZED_NAME_CLIENT_SECRET = "ClientSecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_SECRET)
  @javax.annotation.Nullable
  private String clientSecret;

  public static final String SERIALIZED_NAME_ISSUER = "Issuer";
  @SerializedName(SERIALIZED_NAME_ISSUER)
  @javax.annotation.Nullable
  private String issuer;

  public static final String SERIALIZED_NAME_SCOPES = "Scopes";
  @SerializedName(SERIALIZED_NAME_SCOPES)
  @javax.annotation.Nullable
  private List<String> scopes = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOKEN_AUTH_METHOD = "TokenAuthMethod";
  @SerializedName(SERIALIZED_NAME_TOKEN_AUTH_METHOD)
  @javax.annotation.Nullable
  private String tokenAuthMethod;

  public static final String SERIALIZED_NAME_TOKEN_URL = "TokenUrl";
  @SerializedName(SERIALIZED_NAME_TOKEN_URL)
  @javax.annotation.Nullable
  private String tokenUrl;

  public static final String SERIALIZED_NAME_USER_INFO_URL = "UserInfoUrl";
  @SerializedName(SERIALIZED_NAME_USER_INFO_URL)
  @javax.annotation.Nullable
  private String userInfoUrl;

  /**
   * Type of the connection, which is OIDC in this case.
   */
  @JsonAdapter(ConnectionTypeEnum.Adapter.class)
  public enum ConnectionTypeEnum {
    OIDC_CUSTOM("oidc_custom");

    private String value;

    ConnectionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConnectionTypeEnum fromValue(String value) {
      for (ConnectionTypeEnum b : ConnectionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ConnectionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConnectionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConnectionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConnectionTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ConnectionTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CONNECTION_TYPE = "ConnectionType";
  @SerializedName(SERIALIZED_NAME_CONNECTION_TYPE)
  @javax.annotation.Nullable
  private ConnectionTypeEnum connectionType;

  public static final String SERIALIZED_NAME_REDIRECT_U_R_I = "RedirectURI";
  @SerializedName(SERIALIZED_NAME_REDIRECT_U_R_I)
  @javax.annotation.Nullable
  private String redirectURI;

  public OidcConnectionResponse() {
  }

  public OidcConnectionResponse authorizationUrl(@javax.annotation.Nullable String authorizationUrl) {
    this.authorizationUrl = authorizationUrl;
    return this;
  }

  /**
   * Get authorizationUrl
   * @return authorizationUrl
   */
  @javax.annotation.Nullable
  public String getAuthorizationUrl() {
    return authorizationUrl;
  }

  public void setAuthorizationUrl(@javax.annotation.Nullable String authorizationUrl) {
    this.authorizationUrl = authorizationUrl;
  }


  public OidcConnectionResponse clientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nullable
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }


  public OidcConnectionResponse clientSecret(@javax.annotation.Nullable String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

  /**
   * Get clientSecret
   * @return clientSecret
   */
  @javax.annotation.Nullable
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(@javax.annotation.Nullable String clientSecret) {
    this.clientSecret = clientSecret;
  }


  public OidcConnectionResponse issuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Get issuer
   * @return issuer
   */
  @javax.annotation.Nullable
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(@javax.annotation.Nullable String issuer) {
    this.issuer = issuer;
  }


  public OidcConnectionResponse scopes(@javax.annotation.Nullable List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public OidcConnectionResponse addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

  /**
   * Get scopes
   * @return scopes
   */
  @javax.annotation.Nullable
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(@javax.annotation.Nullable List<String> scopes) {
    this.scopes = scopes;
  }


  public OidcConnectionResponse tokenAuthMethod(@javax.annotation.Nullable String tokenAuthMethod) {
    this.tokenAuthMethod = tokenAuthMethod;
    return this;
  }

  /**
   * Get tokenAuthMethod
   * @return tokenAuthMethod
   */
  @javax.annotation.Nullable
  public String getTokenAuthMethod() {
    return tokenAuthMethod;
  }

  public void setTokenAuthMethod(@javax.annotation.Nullable String tokenAuthMethod) {
    this.tokenAuthMethod = tokenAuthMethod;
  }


  public OidcConnectionResponse tokenUrl(@javax.annotation.Nullable String tokenUrl) {
    this.tokenUrl = tokenUrl;
    return this;
  }

  /**
   * Get tokenUrl
   * @return tokenUrl
   */
  @javax.annotation.Nullable
  public String getTokenUrl() {
    return tokenUrl;
  }

  public void setTokenUrl(@javax.annotation.Nullable String tokenUrl) {
    this.tokenUrl = tokenUrl;
  }


  public OidcConnectionResponse userInfoUrl(@javax.annotation.Nullable String userInfoUrl) {
    this.userInfoUrl = userInfoUrl;
    return this;
  }

  /**
   * Get userInfoUrl
   * @return userInfoUrl
   */
  @javax.annotation.Nullable
  public String getUserInfoUrl() {
    return userInfoUrl;
  }

  public void setUserInfoUrl(@javax.annotation.Nullable String userInfoUrl) {
    this.userInfoUrl = userInfoUrl;
  }


  public OidcConnectionResponse connectionType(@javax.annotation.Nullable ConnectionTypeEnum connectionType) {
    this.connectionType = connectionType;
    return this;
  }

  /**
   * Type of the connection, which is OIDC in this case.
   * @return connectionType
   */
  @javax.annotation.Nullable
  public ConnectionTypeEnum getConnectionType() {
    return connectionType;
  }

  public void setConnectionType(@javax.annotation.Nullable ConnectionTypeEnum connectionType) {
    this.connectionType = connectionType;
  }


  public OidcConnectionResponse redirectURI(@javax.annotation.Nullable String redirectURI) {
    this.redirectURI = redirectURI;
    return this;
  }

  /**
   * The redirect URI for the OIDC connection, where the authorization server will send the user after authentication.
   * @return redirectURI
   */
  @javax.annotation.Nullable
  public String getRedirectURI() {
    return redirectURI;
  }

  public void setRedirectURI(@javax.annotation.Nullable String redirectURI) {
    this.redirectURI = redirectURI;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OidcConnectionResponse oidcConnectionResponse = (OidcConnectionResponse) o;
    return Objects.equals(this.authorizationUrl, oidcConnectionResponse.authorizationUrl) &&
        Objects.equals(this.clientId, oidcConnectionResponse.clientId) &&
        Objects.equals(this.clientSecret, oidcConnectionResponse.clientSecret) &&
        Objects.equals(this.issuer, oidcConnectionResponse.issuer) &&
        Objects.equals(this.scopes, oidcConnectionResponse.scopes) &&
        Objects.equals(this.tokenAuthMethod, oidcConnectionResponse.tokenAuthMethod) &&
        Objects.equals(this.tokenUrl, oidcConnectionResponse.tokenUrl) &&
        Objects.equals(this.userInfoUrl, oidcConnectionResponse.userInfoUrl) &&
        Objects.equals(this.connectionType, oidcConnectionResponse.connectionType) &&
        Objects.equals(this.redirectURI, oidcConnectionResponse.redirectURI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizationUrl, clientId, clientSecret, issuer, scopes, tokenAuthMethod, tokenUrl, userInfoUrl, connectionType, redirectURI);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OidcConnectionResponse {\n");
    sb.append("    authorizationUrl: ").append(toIndentedString(authorizationUrl)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    tokenAuthMethod: ").append(toIndentedString(tokenAuthMethod)).append("\n");
    sb.append("    tokenUrl: ").append(toIndentedString(tokenUrl)).append("\n");
    sb.append("    userInfoUrl: ").append(toIndentedString(userInfoUrl)).append("\n");
    sb.append("    connectionType: ").append(toIndentedString(connectionType)).append("\n");
    sb.append("    redirectURI: ").append(toIndentedString(redirectURI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AuthorizationUrl");
    openapiFields.add("ClientId");
    openapiFields.add("ClientSecret");
    openapiFields.add("Issuer");
    openapiFields.add("Scopes");
    openapiFields.add("TokenAuthMethod");
    openapiFields.add("TokenUrl");
    openapiFields.add("UserInfoUrl");
    openapiFields.add("ConnectionType");
    openapiFields.add("RedirectURI");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OidcConnectionResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OidcConnectionResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OidcConnectionResponse is not found in the empty JSON string", OidcConnectionResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OidcConnectionResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OidcConnectionResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AuthorizationUrl") != null && !jsonObj.get("AuthorizationUrl").isJsonNull()) && !jsonObj.get("AuthorizationUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AuthorizationUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AuthorizationUrl").toString()));
      }
      if ((jsonObj.get("ClientId") != null && !jsonObj.get("ClientId").isJsonNull()) && !jsonObj.get("ClientId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ClientId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ClientId").toString()));
      }
      if ((jsonObj.get("ClientSecret") != null && !jsonObj.get("ClientSecret").isJsonNull()) && !jsonObj.get("ClientSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ClientSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ClientSecret").toString()));
      }
      if ((jsonObj.get("Issuer") != null && !jsonObj.get("Issuer").isJsonNull()) && !jsonObj.get("Issuer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Issuer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Issuer").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("Scopes") != null && !jsonObj.get("Scopes").isJsonNull() && !jsonObj.get("Scopes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `Scopes` to be an array in the JSON string but got `%s`", jsonObj.get("Scopes").toString()));
      }
      if ((jsonObj.get("TokenAuthMethod") != null && !jsonObj.get("TokenAuthMethod").isJsonNull()) && !jsonObj.get("TokenAuthMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TokenAuthMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TokenAuthMethod").toString()));
      }
      if ((jsonObj.get("TokenUrl") != null && !jsonObj.get("TokenUrl").isJsonNull()) && !jsonObj.get("TokenUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TokenUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TokenUrl").toString()));
      }
      if ((jsonObj.get("UserInfoUrl") != null && !jsonObj.get("UserInfoUrl").isJsonNull()) && !jsonObj.get("UserInfoUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `UserInfoUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("UserInfoUrl").toString()));
      }
      if ((jsonObj.get("ConnectionType") != null && !jsonObj.get("ConnectionType").isJsonNull()) && !jsonObj.get("ConnectionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ConnectionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ConnectionType").toString()));
      }
      // validate the optional field `ConnectionType`
      if (jsonObj.get("ConnectionType") != null && !jsonObj.get("ConnectionType").isJsonNull()) {
        ConnectionTypeEnum.validateJsonElement(jsonObj.get("ConnectionType"));
      }
      if ((jsonObj.get("RedirectURI") != null && !jsonObj.get("RedirectURI").isJsonNull()) && !jsonObj.get("RedirectURI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RedirectURI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RedirectURI").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OidcConnectionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OidcConnectionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OidcConnectionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OidcConnectionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OidcConnectionResponse>() {
           @Override
           public void write(JsonWriter out, OidcConnectionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OidcConnectionResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OidcConnectionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OidcConnectionResponse
   * @throws IOException if the JSON string is invalid with respect to OidcConnectionResponse
   */
  public static OidcConnectionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OidcConnectionResponse.class);
  }

  /**
   * Convert an instance of OidcConnectionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

