/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ConnectionResponse;
import org.openapitools.client.model.OrganizationBaseDisplay;
import org.openapitools.client.model.OrganizationsDomainsResponse;
import org.openapitools.client.model.OrganizationsPolicyBase;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OrganizationsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-02T09:39:07.890516193Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class OrganizationsResponse {
  public static final String SERIALIZED_NAME_DISPLAY = "Display";
  @SerializedName(SERIALIZED_NAME_DISPLAY)
  @javax.annotation.Nullable
  private OrganizationBaseDisplay display;

  public static final String SERIALIZED_NAME_DOMAINS = "Domains";
  @SerializedName(SERIALIZED_NAME_DOMAINS)
  @javax.annotation.Nullable
  private List<OrganizationsDomainsResponse> domains;

  public static final String SERIALIZED_NAME_METADATA = "Metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_CONNECTIONS = "Connections";
  @SerializedName(SERIALIZED_NAME_CONNECTIONS)
  @javax.annotation.Nullable
  private List<ConnectionResponse> connections;

  public static final String SERIALIZED_NAME_CREATED_DATE = "CreatedDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime createdDate;

  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "IsActive";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  @javax.annotation.Nullable
  private Boolean isActive;

  public static final String SERIALIZED_NAME_MODIFIED_DATE = "ModifiedDate";
  @SerializedName(SERIALIZED_NAME_MODIFIED_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime modifiedDate;

  public static final String SERIALIZED_NAME_POLICIES = "Policies";
  @SerializedName(SERIALIZED_NAME_POLICIES)
  @javax.annotation.Nullable
  private OrganizationsPolicyBase policies;

  public OrganizationsResponse() {
  }

  public OrganizationsResponse display(@javax.annotation.Nullable OrganizationBaseDisplay display) {
    this.display = display;
    return this;
  }

  /**
   * Get display
   * @return display
   */
  @javax.annotation.Nullable
  public OrganizationBaseDisplay getDisplay() {
    return display;
  }

  public void setDisplay(@javax.annotation.Nullable OrganizationBaseDisplay display) {
    this.display = display;
  }


  public OrganizationsResponse domains(@javax.annotation.Nullable List<OrganizationsDomainsResponse> domains) {
    this.domains = domains;
    return this;
  }

  public OrganizationsResponse addDomainsItem(OrganizationsDomainsResponse domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<>();
    }
    this.domains.add(domainsItem);
    return this;
  }

  /**
   * List of domains associated with the organization
   * @return domains
   */
  @javax.annotation.Nullable
  public List<OrganizationsDomainsResponse> getDomains() {
    return domains;
  }

  public void setDomains(@javax.annotation.Nullable List<OrganizationsDomainsResponse> domains) {
    this.domains = domains;
  }


  public OrganizationsResponse metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public OrganizationsResponse putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Additional metadata for the organization
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public OrganizationsResponse name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the organization
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public OrganizationsResponse connections(@javax.annotation.Nullable List<ConnectionResponse> connections) {
    this.connections = connections;
    return this;
  }

  public OrganizationsResponse addConnectionsItem(ConnectionResponse connectionsItem) {
    if (this.connections == null) {
      this.connections = new ArrayList<>();
    }
    this.connections.add(connectionsItem);
    return this;
  }

  /**
   * List of connections associated with the organization
   * @return connections
   */
  @javax.annotation.Nullable
  public List<ConnectionResponse> getConnections() {
    return connections;
  }

  public void setConnections(@javax.annotation.Nullable List<ConnectionResponse> connections) {
    this.connections = connections;
  }


  public OrganizationsResponse createdDate(@javax.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

  /**
   * Date when the organization was created
   * @return createdDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(@javax.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }


  public OrganizationsResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the organization
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public OrganizationsResponse isActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Indicates whether the organization is active
   * @return isActive
   */
  @javax.annotation.Nullable
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
  }


  public OrganizationsResponse modifiedDate(@javax.annotation.Nullable OffsetDateTime modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

  /**
   * Date when the organization was last modified
   * @return modifiedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(@javax.annotation.Nullable OffsetDateTime modifiedDate) {
    this.modifiedDate = modifiedDate;
  }


  public OrganizationsResponse policies(@javax.annotation.Nullable OrganizationsPolicyBase policies) {
    this.policies = policies;
    return this;
  }

  /**
   * Get policies
   * @return policies
   */
  @javax.annotation.Nullable
  public OrganizationsPolicyBase getPolicies() {
    return policies;
  }

  public void setPolicies(@javax.annotation.Nullable OrganizationsPolicyBase policies) {
    this.policies = policies;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationsResponse organizationsResponse = (OrganizationsResponse) o;
    return Objects.equals(this.display, organizationsResponse.display) &&
        Objects.equals(this.domains, organizationsResponse.domains) &&
        Objects.equals(this.metadata, organizationsResponse.metadata) &&
        Objects.equals(this.name, organizationsResponse.name) &&
        Objects.equals(this.connections, organizationsResponse.connections) &&
        Objects.equals(this.createdDate, organizationsResponse.createdDate) &&
        Objects.equals(this.id, organizationsResponse.id) &&
        Objects.equals(this.isActive, organizationsResponse.isActive) &&
        Objects.equals(this.modifiedDate, organizationsResponse.modifiedDate) &&
        Objects.equals(this.policies, organizationsResponse.policies);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(display, domains, metadata, name, connections, createdDate, id, isActive, modifiedDate, policies);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationsResponse {\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Display");
    openapiFields.add("Domains");
    openapiFields.add("Metadata");
    openapiFields.add("Name");
    openapiFields.add("Connections");
    openapiFields.add("CreatedDate");
    openapiFields.add("Id");
    openapiFields.add("IsActive");
    openapiFields.add("ModifiedDate");
    openapiFields.add("Policies");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrganizationsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganizationsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganizationsResponse is not found in the empty JSON string", OrganizationsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrganizationsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganizationsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Display`
      if (jsonObj.get("Display") != null && !jsonObj.get("Display").isJsonNull()) {
        OrganizationBaseDisplay.validateJsonElement(jsonObj.get("Display"));
      }
      if (jsonObj.get("Domains") != null && !jsonObj.get("Domains").isJsonNull()) {
        JsonArray jsonArraydomains = jsonObj.getAsJsonArray("Domains");
        if (jsonArraydomains != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Domains").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Domains` to be an array in the JSON string but got `%s`", jsonObj.get("Domains").toString()));
          }

          // validate the optional field `Domains` (array)
          for (int i = 0; i < jsonArraydomains.size(); i++) {
            OrganizationsDomainsResponse.validateJsonElement(jsonArraydomains.get(i));
          };
        }
      }
      if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      if (jsonObj.get("Connections") != null && !jsonObj.get("Connections").isJsonNull()) {
        JsonArray jsonArrayconnections = jsonObj.getAsJsonArray("Connections");
        if (jsonArrayconnections != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Connections").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Connections` to be an array in the JSON string but got `%s`", jsonObj.get("Connections").toString()));
          }

          // validate the optional field `Connections` (array)
          for (int i = 0; i < jsonArrayconnections.size(); i++) {
            ConnectionResponse.validateJsonElement(jsonArrayconnections.get(i));
          };
        }
      }
      if ((jsonObj.get("Id") != null && !jsonObj.get("Id").isJsonNull()) && !jsonObj.get("Id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Id").toString()));
      }
      // validate the optional field `Policies`
      if (jsonObj.get("Policies") != null && !jsonObj.get("Policies").isJsonNull()) {
        OrganizationsPolicyBase.validateJsonElement(jsonObj.get("Policies"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationsResponse>() {
           @Override
           public void write(JsonWriter out, OrganizationsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrganizationsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrganizationsResponse
   * @throws IOException if the JSON string is invalid with respect to OrganizationsResponse
   */
  public static OrganizationsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationsResponse.class);
  }

  /**
   * Convert an instance of OrganizationsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

