/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Multi-Factor Authentication (MFA) policy for the organization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-02T09:39:07.890516193Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class OrganizationsPolicyBaseMFAPolicy {
  public static final String SERIALIZED_NAME_ENFORCEMENT_MODE = "EnforcementMode";
  @SerializedName(SERIALIZED_NAME_ENFORCEMENT_MODE)
  @javax.annotation.Nullable
  private String enforcementMode;

  public OrganizationsPolicyBaseMFAPolicy() {
  }

  public OrganizationsPolicyBaseMFAPolicy enforcementMode(@javax.annotation.Nullable String enforcementMode) {
    this.enforcementMode = enforcementMode;
    return this;
  }

  /**
   * Mode of enforcement for Multi-Factor Authentication (MFA)
   * @return enforcementMode
   */
  @javax.annotation.Nullable
  public String getEnforcementMode() {
    return enforcementMode;
  }

  public void setEnforcementMode(@javax.annotation.Nullable String enforcementMode) {
    this.enforcementMode = enforcementMode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationsPolicyBaseMFAPolicy organizationsPolicyBaseMFAPolicy = (OrganizationsPolicyBaseMFAPolicy) o;
    return Objects.equals(this.enforcementMode, organizationsPolicyBaseMFAPolicy.enforcementMode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enforcementMode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationsPolicyBaseMFAPolicy {\n");
    sb.append("    enforcementMode: ").append(toIndentedString(enforcementMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("EnforcementMode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrganizationsPolicyBaseMFAPolicy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganizationsPolicyBaseMFAPolicy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganizationsPolicyBaseMFAPolicy is not found in the empty JSON string", OrganizationsPolicyBaseMFAPolicy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrganizationsPolicyBaseMFAPolicy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganizationsPolicyBaseMFAPolicy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("EnforcementMode") != null && !jsonObj.get("EnforcementMode").isJsonNull()) && !jsonObj.get("EnforcementMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EnforcementMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EnforcementMode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationsPolicyBaseMFAPolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationsPolicyBaseMFAPolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationsPolicyBaseMFAPolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationsPolicyBaseMFAPolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationsPolicyBaseMFAPolicy>() {
           @Override
           public void write(JsonWriter out, OrganizationsPolicyBaseMFAPolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationsPolicyBaseMFAPolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrganizationsPolicyBaseMFAPolicy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrganizationsPolicyBaseMFAPolicy
   * @throws IOException if the JSON string is invalid with respect to OrganizationsPolicyBaseMFAPolicy
   */
  public static OrganizationsPolicyBaseMFAPolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationsPolicyBaseMFAPolicy.class);
  }

  /**
   * Convert an instance of OrganizationsPolicyBaseMFAPolicy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

