/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.OrganizationsConnectionSamlBaseIDPCertificate;
import org.openapitools.client.model.SamlConnectionResponseAllOfSPCertificate;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SamlConnectionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-02T09:39:07.890516193Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class SamlConnectionResponse {
  public static final String SERIALIZED_NAME_ID_P_ENTITY_ID = "IDPEntityId";
  @SerializedName(SERIALIZED_NAME_ID_P_ENTITY_ID)
  @javax.annotation.Nullable
  private String idPEntityId;

  public static final String SERIALIZED_NAME_ID_P_METADATA_URL = "IDPMetadataUrl";
  @SerializedName(SERIALIZED_NAME_ID_P_METADATA_URL)
  @javax.annotation.Nullable
  private String idPMetadataUrl;

  public static final String SERIALIZED_NAME_IS_I_D_P_INITIATED = "IsIDPInitiated";
  @SerializedName(SERIALIZED_NAME_IS_I_D_P_INITIATED)
  @javax.annotation.Nullable
  private Boolean isIDPInitiated;

  public static final String SERIALIZED_NAME_ID_P_CERTIFICATE = "IDPCertificate";
  @SerializedName(SERIALIZED_NAME_ID_P_CERTIFICATE)
  @javax.annotation.Nullable
  private OrganizationsConnectionSamlBaseIDPCertificate idPCertificate;

  /**
   * The type of SAML connection.
   */
  @JsonAdapter(ConnectionTypeEnum.Adapter.class)
  public enum ConnectionTypeEnum {
    SAML_CUSTOM("saml_custom"),
    
    SAML_OKTA("saml_okta"),
    
    SAML_ENTRAID("saml_entraid"),
    
    SAML_GOOGLE_WORKSPACE("saml_google_workspace"),
    
    SAML_SALESFORCE("saml_salesforce");

    private String value;

    ConnectionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConnectionTypeEnum fromValue(String value) {
      for (ConnectionTypeEnum b : ConnectionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ConnectionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConnectionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConnectionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConnectionTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ConnectionTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CONNECTION_TYPE = "ConnectionType";
  @SerializedName(SERIALIZED_NAME_CONNECTION_TYPE)
  @javax.annotation.Nullable
  private ConnectionTypeEnum connectionType;

  public static final String SERIALIZED_NAME_ENTITY_ID = "EntityId";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  @javax.annotation.Nullable
  private String entityId;

  public static final String SERIALIZED_NAME_METADATA_URL = "MetadataUrl";
  @SerializedName(SERIALIZED_NAME_METADATA_URL)
  @javax.annotation.Nullable
  private String metadataUrl;

  public static final String SERIALIZED_NAME_AC_S_ENDPOINT = "ACSEndpoint";
  @SerializedName(SERIALIZED_NAME_AC_S_ENDPOINT)
  @javax.annotation.Nullable
  private String acSEndpoint;

  public static final String SERIALIZED_NAME_SP_CERTIFICATE = "SPCertificate";
  @SerializedName(SERIALIZED_NAME_SP_CERTIFICATE)
  @javax.annotation.Nullable
  private SamlConnectionResponseAllOfSPCertificate spCertificate;

  public SamlConnectionResponse() {
  }

  public SamlConnectionResponse idPEntityId(@javax.annotation.Nullable String idPEntityId) {
    this.idPEntityId = idPEntityId;
    return this;
  }

  /**
   * Unique identifier for the Identity Provider (IdP).
   * @return idPEntityId
   */
  @javax.annotation.Nullable
  public String getIdPEntityId() {
    return idPEntityId;
  }

  public void setIdPEntityId(@javax.annotation.Nullable String idPEntityId) {
    this.idPEntityId = idPEntityId;
  }


  public SamlConnectionResponse idPMetadataUrl(@javax.annotation.Nullable String idPMetadataUrl) {
    this.idPMetadataUrl = idPMetadataUrl;
    return this;
  }

  /**
   * URL to the IdP metadata XML file.
   * @return idPMetadataUrl
   */
  @javax.annotation.Nullable
  public String getIdPMetadataUrl() {
    return idPMetadataUrl;
  }

  public void setIdPMetadataUrl(@javax.annotation.Nullable String idPMetadataUrl) {
    this.idPMetadataUrl = idPMetadataUrl;
  }


  public SamlConnectionResponse isIDPInitiated(@javax.annotation.Nullable Boolean isIDPInitiated) {
    this.isIDPInitiated = isIDPInitiated;
    return this;
  }

  /**
   * Indicates whether the SAML connection is initiated by the IdP.
   * @return isIDPInitiated
   */
  @javax.annotation.Nullable
  public Boolean getIsIDPInitiated() {
    return isIDPInitiated;
  }

  public void setIsIDPInitiated(@javax.annotation.Nullable Boolean isIDPInitiated) {
    this.isIDPInitiated = isIDPInitiated;
  }


  public SamlConnectionResponse idPCertificate(@javax.annotation.Nullable OrganizationsConnectionSamlBaseIDPCertificate idPCertificate) {
    this.idPCertificate = idPCertificate;
    return this;
  }

  /**
   * Get idPCertificate
   * @return idPCertificate
   */
  @javax.annotation.Nullable
  public OrganizationsConnectionSamlBaseIDPCertificate getIdPCertificate() {
    return idPCertificate;
  }

  public void setIdPCertificate(@javax.annotation.Nullable OrganizationsConnectionSamlBaseIDPCertificate idPCertificate) {
    this.idPCertificate = idPCertificate;
  }


  public SamlConnectionResponse connectionType(@javax.annotation.Nullable ConnectionTypeEnum connectionType) {
    this.connectionType = connectionType;
    return this;
  }

  /**
   * The type of SAML connection.
   * @return connectionType
   */
  @javax.annotation.Nullable
  public ConnectionTypeEnum getConnectionType() {
    return connectionType;
  }

  public void setConnectionType(@javax.annotation.Nullable ConnectionTypeEnum connectionType) {
    this.connectionType = connectionType;
  }


  public SamlConnectionResponse entityId(@javax.annotation.Nullable String entityId) {
    this.entityId = entityId;
    return this;
  }

  /**
   * The unique identifier for the SAML service provider.
   * @return entityId
   */
  @javax.annotation.Nullable
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(@javax.annotation.Nullable String entityId) {
    this.entityId = entityId;
  }


  public SamlConnectionResponse metadataUrl(@javax.annotation.Nullable String metadataUrl) {
    this.metadataUrl = metadataUrl;
    return this;
  }

  /**
   * The URL to the SAML metadata XML file.
   * @return metadataUrl
   */
  @javax.annotation.Nullable
  public String getMetadataUrl() {
    return metadataUrl;
  }

  public void setMetadataUrl(@javax.annotation.Nullable String metadataUrl) {
    this.metadataUrl = metadataUrl;
  }


  public SamlConnectionResponse acSEndpoint(@javax.annotation.Nullable String acSEndpoint) {
    this.acSEndpoint = acSEndpoint;
    return this;
  }

  /**
   * The Assertion Consumer Service (ACS) endpoint URL for SAML responses.
   * @return acSEndpoint
   */
  @javax.annotation.Nullable
  public String getAcSEndpoint() {
    return acSEndpoint;
  }

  public void setAcSEndpoint(@javax.annotation.Nullable String acSEndpoint) {
    this.acSEndpoint = acSEndpoint;
  }


  public SamlConnectionResponse spCertificate(@javax.annotation.Nullable SamlConnectionResponseAllOfSPCertificate spCertificate) {
    this.spCertificate = spCertificate;
    return this;
  }

  /**
   * Get spCertificate
   * @return spCertificate
   */
  @javax.annotation.Nullable
  public SamlConnectionResponseAllOfSPCertificate getSpCertificate() {
    return spCertificate;
  }

  public void setSpCertificate(@javax.annotation.Nullable SamlConnectionResponseAllOfSPCertificate spCertificate) {
    this.spCertificate = spCertificate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SamlConnectionResponse samlConnectionResponse = (SamlConnectionResponse) o;
    return Objects.equals(this.idPEntityId, samlConnectionResponse.idPEntityId) &&
        Objects.equals(this.idPMetadataUrl, samlConnectionResponse.idPMetadataUrl) &&
        Objects.equals(this.isIDPInitiated, samlConnectionResponse.isIDPInitiated) &&
        Objects.equals(this.idPCertificate, samlConnectionResponse.idPCertificate) &&
        Objects.equals(this.connectionType, samlConnectionResponse.connectionType) &&
        Objects.equals(this.entityId, samlConnectionResponse.entityId) &&
        Objects.equals(this.metadataUrl, samlConnectionResponse.metadataUrl) &&
        Objects.equals(this.acSEndpoint, samlConnectionResponse.acSEndpoint) &&
        Objects.equals(this.spCertificate, samlConnectionResponse.spCertificate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(idPEntityId, idPMetadataUrl, isIDPInitiated, idPCertificate, connectionType, entityId, metadataUrl, acSEndpoint, spCertificate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SamlConnectionResponse {\n");
    sb.append("    idPEntityId: ").append(toIndentedString(idPEntityId)).append("\n");
    sb.append("    idPMetadataUrl: ").append(toIndentedString(idPMetadataUrl)).append("\n");
    sb.append("    isIDPInitiated: ").append(toIndentedString(isIDPInitiated)).append("\n");
    sb.append("    idPCertificate: ").append(toIndentedString(idPCertificate)).append("\n");
    sb.append("    connectionType: ").append(toIndentedString(connectionType)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    metadataUrl: ").append(toIndentedString(metadataUrl)).append("\n");
    sb.append("    acSEndpoint: ").append(toIndentedString(acSEndpoint)).append("\n");
    sb.append("    spCertificate: ").append(toIndentedString(spCertificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("IDPEntityId");
    openapiFields.add("IDPMetadataUrl");
    openapiFields.add("IsIDPInitiated");
    openapiFields.add("IDPCertificate");
    openapiFields.add("ConnectionType");
    openapiFields.add("EntityId");
    openapiFields.add("MetadataUrl");
    openapiFields.add("ACSEndpoint");
    openapiFields.add("SPCertificate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SamlConnectionResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SamlConnectionResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SamlConnectionResponse is not found in the empty JSON string", SamlConnectionResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SamlConnectionResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SamlConnectionResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("IDPEntityId") != null && !jsonObj.get("IDPEntityId").isJsonNull()) && !jsonObj.get("IDPEntityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `IDPEntityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("IDPEntityId").toString()));
      }
      if ((jsonObj.get("IDPMetadataUrl") != null && !jsonObj.get("IDPMetadataUrl").isJsonNull()) && !jsonObj.get("IDPMetadataUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `IDPMetadataUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("IDPMetadataUrl").toString()));
      }
      // validate the optional field `IDPCertificate`
      if (jsonObj.get("IDPCertificate") != null && !jsonObj.get("IDPCertificate").isJsonNull()) {
        OrganizationsConnectionSamlBaseIDPCertificate.validateJsonElement(jsonObj.get("IDPCertificate"));
      }
      if ((jsonObj.get("ConnectionType") != null && !jsonObj.get("ConnectionType").isJsonNull()) && !jsonObj.get("ConnectionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ConnectionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ConnectionType").toString()));
      }
      // validate the optional field `ConnectionType`
      if (jsonObj.get("ConnectionType") != null && !jsonObj.get("ConnectionType").isJsonNull()) {
        ConnectionTypeEnum.validateJsonElement(jsonObj.get("ConnectionType"));
      }
      if ((jsonObj.get("EntityId") != null && !jsonObj.get("EntityId").isJsonNull()) && !jsonObj.get("EntityId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EntityId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EntityId").toString()));
      }
      if ((jsonObj.get("MetadataUrl") != null && !jsonObj.get("MetadataUrl").isJsonNull()) && !jsonObj.get("MetadataUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MetadataUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MetadataUrl").toString()));
      }
      if ((jsonObj.get("ACSEndpoint") != null && !jsonObj.get("ACSEndpoint").isJsonNull()) && !jsonObj.get("ACSEndpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ACSEndpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ACSEndpoint").toString()));
      }
      // validate the optional field `SPCertificate`
      if (jsonObj.get("SPCertificate") != null && !jsonObj.get("SPCertificate").isJsonNull()) {
        SamlConnectionResponseAllOfSPCertificate.validateJsonElement(jsonObj.get("SPCertificate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SamlConnectionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SamlConnectionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SamlConnectionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SamlConnectionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SamlConnectionResponse>() {
           @Override
           public void write(JsonWriter out, SamlConnectionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SamlConnectionResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SamlConnectionResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SamlConnectionResponse
   * @throws IOException if the JSON string is invalid with respect to SamlConnectionResponse
   */
  public static SamlConnectionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SamlConnectionResponse.class);
  }

  /**
   * Convert an instance of SamlConnectionResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

