/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateInvitationByInvitationIdRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-02T09:39:07.890516193Z[Etc/UTC]", comments = "Generator version: 7.13.0")
public class UpdateInvitationByInvitationIdRequest {
  public static final String SERIALIZED_NAME_ROLES_IDS = "RolesIds";
  @SerializedName(SERIALIZED_NAME_ROLES_IDS)
  @javax.annotation.Nullable
  private List<String> rolesIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_RESEND_EMAIL = "ResendEmail";
  @SerializedName(SERIALIZED_NAME_RESEND_EMAIL)
  @javax.annotation.Nullable
  private Boolean resendEmail;

  public UpdateInvitationByInvitationIdRequest() {
  }

  public UpdateInvitationByInvitationIdRequest rolesIds(@javax.annotation.Nullable List<String> rolesIds) {
    this.rolesIds = rolesIds;
    return this;
  }

  public UpdateInvitationByInvitationIdRequest addRolesIdsItem(String rolesIdsItem) {
    if (this.rolesIds == null) {
      this.rolesIds = new ArrayList<>();
    }
    this.rolesIds.add(rolesIdsItem);
    return this;
  }

  /**
   * The list of role IDs associated with the invitation. Each role ID is typically in the format *role_&lt;unique_id&gt;*, where *&lt;unique_id&gt;* is a string of alphanumeric characters.
   * @return rolesIds
   */
  @javax.annotation.Nullable
  public List<String> getRolesIds() {
    return rolesIds;
  }

  public void setRolesIds(@javax.annotation.Nullable List<String> rolesIds) {
    this.rolesIds = rolesIds;
  }


  public UpdateInvitationByInvitationIdRequest resendEmail(@javax.annotation.Nullable Boolean resendEmail) {
    this.resendEmail = resendEmail;
    return this;
  }

  /**
   * Indicates whether to resend the invitation email. If set to true, the invitation email will be resent to the user.
   * @return resendEmail
   */
  @javax.annotation.Nullable
  public Boolean getResendEmail() {
    return resendEmail;
  }

  public void setResendEmail(@javax.annotation.Nullable Boolean resendEmail) {
    this.resendEmail = resendEmail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest = (UpdateInvitationByInvitationIdRequest) o;
    return Objects.equals(this.rolesIds, updateInvitationByInvitationIdRequest.rolesIds) &&
        Objects.equals(this.resendEmail, updateInvitationByInvitationIdRequest.resendEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rolesIds, resendEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateInvitationByInvitationIdRequest {\n");
    sb.append("    rolesIds: ").append(toIndentedString(rolesIds)).append("\n");
    sb.append("    resendEmail: ").append(toIndentedString(resendEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RolesIds");
    openapiFields.add("ResendEmail");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateInvitationByInvitationIdRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateInvitationByInvitationIdRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateInvitationByInvitationIdRequest is not found in the empty JSON string", UpdateInvitationByInvitationIdRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateInvitationByInvitationIdRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateInvitationByInvitationIdRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("RolesIds") != null && !jsonObj.get("RolesIds").isJsonNull() && !jsonObj.get("RolesIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `RolesIds` to be an array in the JSON string but got `%s`", jsonObj.get("RolesIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateInvitationByInvitationIdRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateInvitationByInvitationIdRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateInvitationByInvitationIdRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateInvitationByInvitationIdRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateInvitationByInvitationIdRequest>() {
           @Override
           public void write(JsonWriter out, UpdateInvitationByInvitationIdRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateInvitationByInvitationIdRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateInvitationByInvitationIdRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateInvitationByInvitationIdRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateInvitationByInvitationIdRequest
   */
  public static UpdateInvitationByInvitationIdRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateInvitationByInvitationIdRequest.class);
  }

  /**
   * Convert an instance of UpdateInvitationByInvitationIdRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

