/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetInvitationsByOrgId200Response;
import org.openapitools.client.model.Invitation;
import org.openapitools.client.model.ResendInvitation;
import org.openapitools.client.model.SendInvitation;
import org.openapitools.client.model.UpdateInvitationByInvitationIdRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvitationsApi
 */
@Disabled
public class InvitationsApiTest {

    private final InvitationsApi api = new InvitationsApi();

    /**
     * Delete/Revoke invitation by invitation id
     *
     * Delete or revoke an invitation by invitation id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInvitationByInvitationIdTest() throws ApiException {
        String invitationid = null;
        Invitation response = api.deleteInvitationByInvitationId(invitationid);
        // TODO: test validations
    }

    /**
     * Get invitation by invitation id
     *
     * Get invitation details by invitation ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInvitationByInvitationIdTest() throws ApiException {
        String invitationid = null;
        Invitation response = api.getInvitationByInvitationId(invitationid);
        // TODO: test validations
    }

    /**
     * Get all invitations By Org id
     *
     * Get all invitations By Org id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInvitationsByOrgIdTest() throws ApiException {
        String orgid = null;
        GetInvitationsByOrgId200Response response = api.getInvitationsByOrgId(orgid);
        // TODO: test validations
    }

    /**
     * Resend invitation by ID
     *
     * Resend invitation details by invitation id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resendInvitationByInvitationIdTest() throws ApiException {
        String invitationid = null;
        ResendInvitation response = api.resendInvitationByInvitationId(invitationid);
        // TODO: test validations
    }

    /**
     * Send new invitation
     *
     * Send a new invitation
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendInvitationTest() throws ApiException {
        SendInvitation sendInvitation = null;
        String invitationUrl = null;
        Invitation response = api.sendInvitation(sendInvitation, invitationUrl);
        // TODO: test validations
    }

    /**
     * Update invitation by invitation id
     *
     * Update invitation details by invitation id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateInvitationByInvitationIdTest() throws ApiException {
        UpdateInvitationByInvitationIdRequest updateInvitationByInvitationIdRequest = null;
        String invitationid = null;
        String invitationUrl = null;
        Invitation response = api.updateInvitationByInvitationId(updateInvitationByInvitationIdRequest, invitationid, invitationUrl);
        // TODO: test validations
    }

}
