/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ConnectionGroupRoleRequest;
import org.openapitools.client.model.ConnectionGroupRoleResponse;
import org.openapitools.client.model.CreateConnectionGroupRoleRequest;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetAllConnectionGroupRoles200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationConnectionGroupRolesApi
 */
@Disabled
public class OrganizationConnectionGroupRolesApiTest {

    private final OrganizationConnectionGroupRolesApi api = new OrganizationConnectionGroupRolesApi();

    /**
     * Create Organization Connection Group Roles
     *
     * Create a new group-to-role mapping for an identity provider connection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createConnectionGroupRoleTest() throws ApiException {
        CreateConnectionGroupRoleRequest createConnectionGroupRoleRequest = null;
        String connId = null;
        String orgId = null;
        ConnectionGroupRoleResponse response = api.createConnectionGroupRole(createConnectionGroupRoleRequest, connId, orgId);
        // TODO: test validations
    }

    /**
     * Delete Organization Connection Group Roles
     *
     * Delete a specific group-to-role mapping
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteConnectionGroupRoleTest() throws ApiException {
        String orgId = null;
        String connId = null;
        String groupRoleId = null;
        DeleteResponse response = api.deleteConnectionGroupRole(orgId, connId, groupRoleId);
        // TODO: test validations
    }

    /**
     * Get All Organization Connection Group Roles
     *
     * Get all group-to-role mappings for an identity provider connection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllConnectionGroupRolesTest() throws ApiException {
        String orgId = null;
        String connId = null;
        GetAllConnectionGroupRoles200Response response = api.getAllConnectionGroupRoles(orgId, connId);
        // TODO: test validations
    }

    /**
     * Update Organization Connection Group Roles
     *
     * Update a specific group-to-role mapping
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateConnectionGroupRoleTest() throws ApiException {
        ConnectionGroupRoleRequest connectionGroupRoleRequest = null;
        String connId = null;
        String groupRoleId = null;
        String orgId = null;
        ConnectionGroupRoleResponse response = api.updateConnectionGroupRole(connectionGroupRoleRequest, connId, groupRoleId, orgId);
        // TODO: test validations
    }

}
