/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AddOrganizationDomainRequest;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetAllOrganizationDomains200Response;
import org.openapitools.client.model.OrganizationsDomainsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationDomainsApi
 */
@Disabled
public class OrganizationDomainsApiTest {

    private final OrganizationDomainsApi api = new OrganizationDomainsApi();

    /**
     * Add Organization Domain
     *
     * Add Organization Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addOrganizationDomainTest() throws ApiException {
        AddOrganizationDomainRequest addOrganizationDomainRequest = null;
        String orgId = null;
        OrganizationsDomainsResponse response = api.addOrganizationDomain(addOrganizationDomainRequest, orgId);
        // TODO: test validations
    }

    /**
     * Delete Organization Domain
     *
     * Delete Organization Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteOrganizationDomainTest() throws ApiException {
        String orgId = null;
        String domainId = null;
        DeleteResponse response = api.deleteOrganizationDomain(orgId, domainId);
        // TODO: test validations
    }

    /**
     * List of Organization Domains
     *
     * Get all domains associated with an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllOrganizationDomainsTest() throws ApiException {
        String orgId = null;
        GetAllOrganizationDomains200Response response = api.getAllOrganizationDomains(orgId);
        // TODO: test validations
    }

    /**
     * Get Organization Domain
     *
     * Get Organization Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrganizationDomainTest() throws ApiException {
        String orgId = null;
        String domainId = null;
        OrganizationsDomainsResponse response = api.getOrganizationDomain(orgId, domainId);
        // TODO: test validations
    }

    /**
     * Verify Organization Domain
     *
     * Verify Organization Domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyOrganizationDomainTest() throws ApiException {
        String domainId = null;
        String orgId = null;
        OrganizationsDomainsResponse response = api.verifyOrganizationDomain(domainId, orgId);
        // TODO: test validations
    }

}
