/*
 * Partner IAM API
 * Partner IAM API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@loginradius.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DeleteResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.PermissionPutRequest;
import org.openapitools.client.model.Permissions;
import org.openapitools.client.model.Permissions200Response;
import org.openapitools.client.model.PermissionsPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PermissionsApi
 */
@Disabled
public class PermissionsApiTest {

    private final PermissionsApi api = new PermissionsApi();

    /**
     * Add Permission
     *
     * Add a new permission
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addPermissionTest() throws ApiException {
        PermissionsPostRequest permissionsPostRequest = null;
        Permissions response = api.addPermission(permissionsPostRequest);
        // TODO: test validations
    }

    /**
     * Delete Permission
     *
     * Delete a permission
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePermissionTest() throws ApiException {
        String id = null;
        DeleteResponse response = api.deletePermission(id);
        // TODO: test validations
    }

    /**
     * Get Permission by Id
     *
     * Get a permission by its ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPermissionByIdTest() throws ApiException {
        String id = null;
        Permissions response = api.getPermissionById(id);
        // TODO: test validations
    }

    /**
     * Get Permission list
     *
     * Get the list of permissions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void permissionsTest() throws ApiException {
        Permissions200Response response = api.permissions();
        // TODO: test validations
    }

    /**
     * Update Permission
     *
     * Update a permission
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePermissionTest() throws ApiException {
        String id = null;
        PermissionPutRequest permissionPutRequest = null;
        Permissions response = api.updatePermission(id, permissionPutRequest);
        // TODO: test validations
    }

}
